/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package deploy_components

import (
	"encoding/json"
	"errors"

	"github.com/kubevela/vela-go-sdk/pkg/apis/utils"
)

// checks if the Components type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Components{}

// Components struct for Components
type Components struct {
	// the name of the component in the application to apply
	Name *string `json:"name"`
	// names of topology policies (declared at the Application level) used to resolve this component's target cluster(s)
	Policies []string `json:"policies"`
}

// NewComponentsWith instantiates a new Components object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewComponentsWith(name string, policies []string) *Components {
	this := Components{}
	this.Name = &name
	this.Policies = policies
	return &this
}

// NewComponentsWithDefault instantiates a new Components object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComponentsWithDefault() *Components {
	this := Components{}
	return &this
}

// NewComponents is short for NewComponentsWithDefault which instantiates a new Components object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComponents() *Components {
	return NewComponentsWithDefault()
}

// NewComponentsEmpty instantiates a new Components object with no properties set.
// This constructor will not assign any default values to properties.
func NewComponentsEmpty() *Components {
	this := Components{}
	return &this
}

// NewComponentss converts a list Components pointers to objects.
// This is helpful when the SetComponents requires a list of objects
func NewComponentsList(ps ...*Components) []Components {
	objs := []Components{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this Components
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *Components) Validate() error {
	if o.Name == nil {
		return errors.New("Name in Components must be set")
	}
	if o.Policies == nil {
		return errors.New("Policies in Components must be set")
	}
	// validate all nested properties
	return nil
}

// GetName returns the Name field value
func (o *Components) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return *o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Components) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name, true
}

// SetName sets field value
func (o *Components) SetName(v string) *Components {
	o.Name = &v
	return o
}

// GetPolicies returns the Policies field value
func (o *Components) GetPolicies() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Policies
}

// GetPoliciesOk returns a tuple with the Policies field value
// and a boolean to check if the value has been set.
func (o *Components) GetPoliciesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Policies, true
}

// SetPolicies sets field value
func (o *Components) SetPolicies(v []string) *Components {
	o.Policies = v
	return o
}

func (o Components) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Components) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["policies"] = o.Policies
	return toSerialize, nil
}

type NullableComponents struct {
	value *Components
	isSet bool
}

func (v *NullableComponents) Get() *Components {
	return v.value
}

func (v *NullableComponents) Set(val *Components) {
	v.value = val
	v.isSet = true
}

func (v *NullableComponents) IsSet() bool {
	return v.isSet
}

func (v *NullableComponents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComponents(val *Components) *NullableComponents {
	return &NullableComponents{value: val, isSet: true}
}

func (v NullableComponents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComponents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
