/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package deploy_components

import (
	"encoding/json"
	"errors"

	"github.com/oam-dev/kubevela-core-api/pkg/oam/util"

	"github.com/kubevela/pkg/apis/oam/v1alpha1"
	"github.com/kubevela/vela-go-sdk/pkg/apis"
	sdkcommon "github.com/kubevela/vela-go-sdk/pkg/apis/common"
	"github.com/kubevela/vela-go-sdk/pkg/apis/utils"
)

// checks if the DeployComponentsSpec type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &DeployComponentsSpec{}

// DeployComponentsSpec struct for DeployComponentsSpec
type DeployComponentsSpec struct {
	// Per-component mapping of which topology policies determine its target cluster(s)
	Components []Components `json:"components"`
}

// NewDeployComponentsSpecWith instantiates a new DeployComponentsSpec object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewDeployComponentsSpecWith(components []Components) *DeployComponentsSpec {
	this := DeployComponentsSpec{}
	this.Components = components
	return &this
}

// NewDeployComponentsSpecWithDefault instantiates a new DeployComponentsSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeployComponentsSpecWithDefault() *DeployComponentsSpec {
	this := DeployComponentsSpec{}
	return &this
}

// NewDeployComponentsSpec is short for NewDeployComponentsSpecWithDefault which instantiates a new DeployComponentsSpec object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeployComponentsSpec() *DeployComponentsSpec {
	return NewDeployComponentsSpecWithDefault()
}

// NewDeployComponentsSpecEmpty instantiates a new DeployComponentsSpec object with no properties set.
// This constructor will not assign any default values to properties.
func NewDeployComponentsSpecEmpty() *DeployComponentsSpec {
	this := DeployComponentsSpec{}
	return &this
}

// NewDeployComponentsSpecs converts a list DeployComponentsSpec pointers to objects.
// This is helpful when the SetDeployComponentsSpec requires a list of objects
func NewDeployComponentsSpecList(ps ...*DeployComponentsSpec) []DeployComponentsSpec {
	objs := []DeployComponentsSpec{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this DeployComponentsSpec
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *DeployComponentsWorkflowStep) Validate() error {
	if o.Properties.Components == nil {
		return errors.New("Components in DeployComponentsSpec must be set")
	}
	// validate all nested properties
	return nil
}

// GetComponents returns the Components field value
func (o *DeployComponentsWorkflowStep) GetComponents() []Components {
	if o == nil {
		var ret []Components
		return ret
	}

	return o.Properties.Components
}

// GetComponentsOk returns a tuple with the Components field value
// and a boolean to check if the value has been set.
func (o *DeployComponentsWorkflowStep) GetComponentsOk() ([]Components, bool) {
	if o == nil {
		return nil, false
	}
	return o.Properties.Components, true
}

// SetComponents sets field value
func (o *DeployComponentsWorkflowStep) SetComponents(v []Components) *DeployComponentsWorkflowStep {
	o.Properties.Components = v
	return o
}

func (o DeployComponentsSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeployComponentsSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["components"] = o.Components
	return toSerialize, nil
}

type NullableDeployComponentsSpec struct {
	value *DeployComponentsSpec
	isSet bool
}

func (v *NullableDeployComponentsSpec) Get() *DeployComponentsSpec {
	return v.value
}

func (v *NullableDeployComponentsSpec) Set(val *DeployComponentsSpec) {
	v.value = val
	v.isSet = true
}

func (v *NullableDeployComponentsSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableDeployComponentsSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeployComponentsSpec(val *DeployComponentsSpec) *NullableDeployComponentsSpec {
	return &NullableDeployComponentsSpec{value: val, isSet: true}
}

func (v NullableDeployComponentsSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeployComponentsSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

const DeployComponentsType = "deploy-components"

func init() {
	sdkcommon.RegisterWorkflowStep(DeployComponentsType, FromWorkflowStep)
	sdkcommon.RegisterWorkflowSubStep(DeployComponentsType, FromWorkflowSubStep)
}

type DeployComponentsWorkflowStep struct {
	Base       apis.WorkflowStepBase
	Properties DeployComponentsSpec
}

func DeployComponents(name string) *DeployComponentsWorkflowStep {
	d := &DeployComponentsWorkflowStep{Base: apis.WorkflowStepBase{
		Name: name,
		Type: DeployComponentsType,
	}}
	return d
}

func (d *DeployComponentsWorkflowStep) Build() v1alpha1.WorkflowStep {
	_subSteps := make([]v1alpha1.WorkflowStep, 0)
	for _, subStep := range d.Base.SubSteps {
		_subSteps = append(_subSteps, subStep.Build())
	}
	subSteps := make([]v1alpha1.WorkflowStepBase, 0)
	for _, _s := range _subSteps {
		subSteps = append(subSteps, _s.WorkflowStepBase)
	}
	res := v1alpha1.WorkflowStep{
		SubSteps: subSteps,
		WorkflowStepBase: v1alpha1.WorkflowStepBase{
			DependsOn:  d.Base.DependsOn,
			If:         d.Base.If,
			Inputs:     d.Base.Inputs,
			Meta:       d.Base.Meta,
			Name:       d.Base.Name,
			Outputs:    d.Base.Outputs,
			Properties: util.Object2RawExtension(d.Properties),
			Timeout:    d.Base.Timeout,
			Type:       DeployComponentsType,
		},
	}
	return res
}

func (d *DeployComponentsWorkflowStep) FromWorkflowStep(from v1alpha1.WorkflowStep) (*DeployComponentsWorkflowStep, error) {
	var properties DeployComponentsSpec
	if from.Properties != nil {
		err := json.Unmarshal(from.Properties.Raw, &properties)
		if err != nil {
			return nil, err
		}
	}
	subSteps := make([]apis.WorkflowStep, 0)
	for _, _s := range from.SubSteps {
		subStep, err := d.FromWorkflowSubStep(_s)
		if err != nil {
			return nil, err
		}
		subSteps = append(subSteps, subStep)
	}
	d.Base.Name = from.Name
	d.Base.DependsOn = from.DependsOn
	d.Base.Inputs = from.Inputs
	d.Base.Outputs = from.Outputs
	d.Base.If = from.If
	d.Base.Timeout = from.Timeout
	d.Base.Meta = from.Meta
	d.Base.Type = DeployComponentsType
	d.Properties = properties
	d.Base.SubSteps = subSteps
	return d, nil
}

func FromWorkflowStep(from v1alpha1.WorkflowStep) (apis.WorkflowStep, error) {
	d := &DeployComponentsWorkflowStep{}
	return d.FromWorkflowStep(from)
}

func (d *DeployComponentsWorkflowStep) FromWorkflowSubStep(from v1alpha1.WorkflowStepBase) (*DeployComponentsWorkflowStep, error) {
	var properties DeployComponentsSpec
	if from.Properties != nil {
		err := json.Unmarshal(from.Properties.Raw, &properties)
		if err != nil {
			return nil, err
		}
	}
	d.Base.Name = from.Name
	d.Base.DependsOn = from.DependsOn
	d.Base.Inputs = from.Inputs
	d.Base.Outputs = from.Outputs
	d.Base.If = from.If
	d.Base.Timeout = from.Timeout
	d.Base.Meta = from.Meta
	d.Base.Type = DeployComponentsType
	d.Properties = properties
	return d, nil
}

func FromWorkflowSubStep(from v1alpha1.WorkflowStepBase) (apis.WorkflowStep, error) {
	d := &DeployComponentsWorkflowStep{}
	return d.FromWorkflowSubStep(from)
}

func (d *DeployComponentsWorkflowStep) WorkflowStepName() string {
	return d.Base.Name
}

func (d *DeployComponentsWorkflowStep) DefType() string {
	return DeployComponentsType
}

func (d *DeployComponentsWorkflowStep) If(_if string) *DeployComponentsWorkflowStep {
	d.Base.If = _if
	return d
}

func (d *DeployComponentsWorkflowStep) Alias(alias string) *DeployComponentsWorkflowStep {
	d.Base.Meta.Alias = alias
	return d
}

func (d *DeployComponentsWorkflowStep) Timeout(timeout string) *DeployComponentsWorkflowStep {
	d.Base.Timeout = timeout
	return d
}

func (d *DeployComponentsWorkflowStep) DependsOn(dependsOn []string) *DeployComponentsWorkflowStep {
	d.Base.DependsOn = dependsOn
	return d
}

func (d *DeployComponentsWorkflowStep) Inputs(input v1alpha1.StepInputs) *DeployComponentsWorkflowStep {
	d.Base.Inputs = input
	return d
}

func (d *DeployComponentsWorkflowStep) Outputs(output v1alpha1.StepOutputs) *DeployComponentsWorkflowStep {
	d.Base.Outputs = output
	return d
}
