apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: pol-apply-once
  namespace: trace-r2
  annotations:
    app.oam.dev/traceID: trace-r2-apply-once-fixed
spec:
  components:
    - name: once
      type: webservice
      properties:
        image: nginx:1.21
  policies:
    - name: apply-once-rule
      type: apply-once
      properties:
        enable: true
