apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-failing
  namespace: trace-r2
  annotations:
    app.oam.dev/traceID: trace-r2-failing-fixed
spec:
  components:
    - name: bad-image
      type: webservice
      properties:
        image: this-image-does-not-exist:invalid-tag-xyz
