apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-implicit
  namespace: trace-r2
  annotations:
    app.oam.dev/traceID: trace-r2-implicit-fixed
spec:
  components:
    - name: impl
      type: webservice
      properties:
        image: nginx:1.21
    - name: side
      type: worker
      properties:
        image: busybox
        cmd: ["sleep", "1000"]
