/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package helmchart

import (
	"encoding/json"

	"github.com/kubevela/vela-go-sdk/pkg/apis/utils"
)

// checks if the Auth type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Auth{}

// Auth struct for Auth
type Auth struct {
	SecretRef *SecretRef `json:"secretRef,omitempty"`
}

// NewAuthWith instantiates a new Auth object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewAuthWith() *Auth {
	this := Auth{}
	return &this
}

// NewAuthWithDefault instantiates a new Auth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthWithDefault() *Auth {
	this := Auth{}
	return &this
}

// NewAuth is short for NewAuthWithDefault which instantiates a new Auth object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuth() *Auth {
	return NewAuthWithDefault()
}

// NewAuthEmpty instantiates a new Auth object with no properties set.
// This constructor will not assign any default values to properties.
func NewAuthEmpty() *Auth {
	this := Auth{}
	return &this
}

// NewAuths converts a list Auth pointers to objects.
// This is helpful when the SetAuth requires a list of objects
func NewAuthList(ps ...*Auth) []Auth {
	objs := []Auth{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this Auth
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *Auth) Validate() error {
	// validate all nested properties
	if o.SecretRef != nil {
		if err := o.SecretRef.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// GetSecretRef returns the SecretRef field value if set, zero value otherwise.
func (o *Auth) GetSecretRef() SecretRef {
	if o == nil || utils.IsNil(o.SecretRef) {
		var ret SecretRef
		return ret
	}
	return *o.SecretRef
}

// GetSecretRefOk returns a tuple with the SecretRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Auth) GetSecretRefOk() (*SecretRef, bool) {
	if o == nil || utils.IsNil(o.SecretRef) {
		return nil, false
	}
	return o.SecretRef, true
}

// HasSecretRef returns a boolean if a field has been set.
func (o *Auth) HasSecretRef() bool {
	if o != nil && !utils.IsNil(o.SecretRef) {
		return true
	}

	return false
}

// SetSecretRef gets a reference to the given SecretRef and assigns it to the secretRef field.
// SecretRef:
func (o *Auth) SetSecretRef(v SecretRef) *Auth {
	o.SecretRef = &v
	return o
}

func (o Auth) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Auth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.SecretRef) {
		toSerialize["secretRef"] = o.SecretRef
	}
	return toSerialize, nil
}

type NullableAuth struct {
	value *Auth
	isSet bool
}

func (v *NullableAuth) Get() *Auth {
	return v.value
}

func (v *NullableAuth) Set(val *Auth) {
	v.value = val
	v.isSet = true
}

func (v *NullableAuth) IsSet() bool {
	return v.isSet
}

func (v *NullableAuth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuth(val *Auth) *NullableAuth {
	return &NullableAuth{value: val, isSet: true}
}

func (v NullableAuth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
