/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package helmchart

import (
	"encoding/json"

	"github.com/kubevela/vela-go-sdk/pkg/apis/utils"
)

// checks if the Cache type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Cache{}

// Cache struct for Cache
type Cache struct {
	ImmutableTTL *string `json:"immutableTTL,omitempty"`
	Key          *string `json:"key,omitempty"`
	MutableTTL   *string `json:"mutableTTL,omitempty"`
	Ttl          *string `json:"ttl,omitempty"`
}

// NewCacheWith instantiates a new Cache object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewCacheWith() *Cache {
	this := Cache{}
	var immutableTTL string = "24h"
	this.ImmutableTTL = &immutableTTL
	var mutableTTL string = "5m"
	this.MutableTTL = &mutableTTL
	return &this
}

// NewCacheWithDefault instantiates a new Cache object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheWithDefault() *Cache {
	this := Cache{}
	var immutableTTL string = "24h"
	this.ImmutableTTL = &immutableTTL
	var mutableTTL string = "5m"
	this.MutableTTL = &mutableTTL
	return &this
}

// NewCache is short for NewCacheWithDefault which instantiates a new Cache object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCache() *Cache {
	return NewCacheWithDefault()
}

// NewCacheEmpty instantiates a new Cache object with no properties set.
// This constructor will not assign any default values to properties.
func NewCacheEmpty() *Cache {
	this := Cache{}
	return &this
}

// NewCaches converts a list Cache pointers to objects.
// This is helpful when the SetCache requires a list of objects
func NewCacheList(ps ...*Cache) []Cache {
	objs := []Cache{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this Cache
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *Cache) Validate() error {
	// validate all nested properties
	return nil
}

// GetImmutableTTL returns the ImmutableTTL field value if set, zero value otherwise.
func (o *Cache) GetImmutableTTL() string {
	if o == nil || utils.IsNil(o.ImmutableTTL) {
		var ret string
		return ret
	}
	return *o.ImmutableTTL
}

// GetImmutableTTLOk returns a tuple with the ImmutableTTL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cache) GetImmutableTTLOk() (*string, bool) {
	if o == nil || utils.IsNil(o.ImmutableTTL) {
		return nil, false
	}
	return o.ImmutableTTL, true
}

// HasImmutableTTL returns a boolean if a field has been set.
func (o *Cache) HasImmutableTTL() bool {
	if o != nil && !utils.IsNil(o.ImmutableTTL) {
		return true
	}

	return false
}

// SetImmutableTTL gets a reference to the given string and assigns it to the immutableTTL field.
// ImmutableTTL:
func (o *Cache) SetImmutableTTL(v string) *Cache {
	o.ImmutableTTL = &v
	return o
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *Cache) GetKey() string {
	if o == nil || utils.IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cache) GetKeyOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *Cache) HasKey() bool {
	if o != nil && !utils.IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the key field.
// Key:
func (o *Cache) SetKey(v string) *Cache {
	o.Key = &v
	return o
}

// GetMutableTTL returns the MutableTTL field value if set, zero value otherwise.
func (o *Cache) GetMutableTTL() string {
	if o == nil || utils.IsNil(o.MutableTTL) {
		var ret string
		return ret
	}
	return *o.MutableTTL
}

// GetMutableTTLOk returns a tuple with the MutableTTL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cache) GetMutableTTLOk() (*string, bool) {
	if o == nil || utils.IsNil(o.MutableTTL) {
		return nil, false
	}
	return o.MutableTTL, true
}

// HasMutableTTL returns a boolean if a field has been set.
func (o *Cache) HasMutableTTL() bool {
	if o != nil && !utils.IsNil(o.MutableTTL) {
		return true
	}

	return false
}

// SetMutableTTL gets a reference to the given string and assigns it to the mutableTTL field.
// MutableTTL:
func (o *Cache) SetMutableTTL(v string) *Cache {
	o.MutableTTL = &v
	return o
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *Cache) GetTtl() string {
	if o == nil || utils.IsNil(o.Ttl) {
		var ret string
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cache) GetTtlOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *Cache) HasTtl() bool {
	if o != nil && !utils.IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given string and assigns it to the ttl field.
// Ttl:
func (o *Cache) SetTtl(v string) *Cache {
	o.Ttl = &v
	return o
}

func (o Cache) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Cache) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.ImmutableTTL) {
		toSerialize["immutableTTL"] = o.ImmutableTTL
	}
	if !utils.IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !utils.IsNil(o.MutableTTL) {
		toSerialize["mutableTTL"] = o.MutableTTL
	}
	if !utils.IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	return toSerialize, nil
}

type NullableCache struct {
	value *Cache
	isSet bool
}

func (v *NullableCache) Get() *Cache {
	return v.value
}

func (v *NullableCache) Set(val *Cache) {
	v.value = val
	v.isSet = true
}

func (v *NullableCache) IsSet() bool {
	return v.isSet
}

func (v *NullableCache) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCache(val *Cache) *NullableCache {
	return &NullableCache{value: val, isSet: true}
}

func (v NullableCache) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCache) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
