/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package helmchart

import (
	"encoding/json"
	"errors"

	"github.com/kubevela/vela-go-sdk/pkg/apis/utils"
)

// checks if the Chart type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Chart{}

// Chart struct for Chart
type Chart struct {
	Auth    *Auth   `json:"auth,omitempty"`
	RepoURL *string `json:"repoURL,omitempty"`
	Source  *string `json:"source"`
	Version *string `json:"version,omitempty"`
}

// NewChartWith instantiates a new Chart object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewChartWith(source string) *Chart {
	this := Chart{}
	this.Source = &source
	var version string = "latest"
	this.Version = &version
	return &this
}

// NewChartWithDefault instantiates a new Chart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChartWithDefault() *Chart {
	this := Chart{}
	var version string = "latest"
	this.Version = &version
	return &this
}

// NewChart is short for NewChartWithDefault which instantiates a new Chart object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChart() *Chart {
	return NewChartWithDefault()
}

// NewChartEmpty instantiates a new Chart object with no properties set.
// This constructor will not assign any default values to properties.
func NewChartEmpty() *Chart {
	this := Chart{}
	return &this
}

// NewCharts converts a list Chart pointers to objects.
// This is helpful when the SetChart requires a list of objects
func NewChartList(ps ...*Chart) []Chart {
	objs := []Chart{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this Chart
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *Chart) Validate() error {
	if o.Source == nil {
		return errors.New("Source in Chart must be set")
	}
	// validate all nested properties
	if o.Auth != nil {
		if err := o.Auth.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// GetAuth returns the Auth field value if set, zero value otherwise.
func (o *Chart) GetAuth() Auth {
	if o == nil || utils.IsNil(o.Auth) {
		var ret Auth
		return ret
	}
	return *o.Auth
}

// GetAuthOk returns a tuple with the Auth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Chart) GetAuthOk() (*Auth, bool) {
	if o == nil || utils.IsNil(o.Auth) {
		return nil, false
	}
	return o.Auth, true
}

// HasAuth returns a boolean if a field has been set.
func (o *Chart) HasAuth() bool {
	if o != nil && !utils.IsNil(o.Auth) {
		return true
	}

	return false
}

// SetAuth gets a reference to the given Auth and assigns it to the auth field.
// Auth:
func (o *Chart) SetAuth(v Auth) *Chart {
	o.Auth = &v
	return o
}

// GetRepoURL returns the RepoURL field value if set, zero value otherwise.
func (o *Chart) GetRepoURL() string {
	if o == nil || utils.IsNil(o.RepoURL) {
		var ret string
		return ret
	}
	return *o.RepoURL
}

// GetRepoURLOk returns a tuple with the RepoURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Chart) GetRepoURLOk() (*string, bool) {
	if o == nil || utils.IsNil(o.RepoURL) {
		return nil, false
	}
	return o.RepoURL, true
}

// HasRepoURL returns a boolean if a field has been set.
func (o *Chart) HasRepoURL() bool {
	if o != nil && !utils.IsNil(o.RepoURL) {
		return true
	}

	return false
}

// SetRepoURL gets a reference to the given string and assigns it to the repoURL field.
// RepoURL:
func (o *Chart) SetRepoURL(v string) *Chart {
	o.RepoURL = &v
	return o
}

// GetSource returns the Source field value
func (o *Chart) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *Chart) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Source, true
}

// SetSource sets field value
func (o *Chart) SetSource(v string) *Chart {
	o.Source = &v
	return o
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *Chart) GetVersion() string {
	if o == nil || utils.IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Chart) GetVersionOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *Chart) HasVersion() bool {
	if o != nil && !utils.IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the version field.
// Version:
func (o *Chart) SetVersion(v string) *Chart {
	o.Version = &v
	return o
}

func (o Chart) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Chart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Auth) {
		toSerialize["auth"] = o.Auth
	}
	if !utils.IsNil(o.RepoURL) {
		toSerialize["repoURL"] = o.RepoURL
	}
	toSerialize["source"] = o.Source
	if !utils.IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableChart struct {
	value *Chart
	isSet bool
}

func (v *NullableChart) Get() *Chart {
	return v.value
}

func (v *NullableChart) Set(val *Chart) {
	v.value = val
	v.isSet = true
}

func (v *NullableChart) IsSet() bool {
	return v.isSet
}

func (v *NullableChart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChart(val *Chart) *NullableChart {
	return &NullableChart{value: val, isSet: true}
}

func (v NullableChart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
