/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package helmchart

import (
	"encoding/json"
	"errors"

	"github.com/kubevela/vela-go-sdk/pkg/apis/utils"
)

// checks if the Condition type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Condition{}

// Condition struct for Condition
type Condition struct {
	Status *string `json:"status,omitempty"`
	Type   *string `json:"type"`
}

// NewConditionWith instantiates a new Condition object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewConditionWith(type_ string) *Condition {
	this := Condition{}
	this.Type = &type_
	return &this
}

// NewConditionWithDefault instantiates a new Condition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConditionWithDefault() *Condition {
	this := Condition{}
	return &this
}

// NewCondition is short for NewConditionWithDefault which instantiates a new Condition object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCondition() *Condition {
	return NewConditionWithDefault()
}

// NewConditionEmpty instantiates a new Condition object with no properties set.
// This constructor will not assign any default values to properties.
func NewConditionEmpty() *Condition {
	this := Condition{}
	return &this
}

// NewConditions converts a list Condition pointers to objects.
// This is helpful when the SetCondition requires a list of objects
func NewConditionList(ps ...*Condition) []Condition {
	objs := []Condition{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this Condition
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *Condition) Validate() error {
	if o.Type == nil {
		return errors.New("Type in Condition must be set")
	}
	// validate all nested properties
	return nil
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Condition) GetStatus() string {
	if o == nil || utils.IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Condition) GetStatusOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Condition) HasStatus() bool {
	if o != nil && !utils.IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the status field.
// Status:
func (o *Condition) SetStatus(v string) *Condition {
	o.Status = &v
	return o
}

// GetType returns the Type field value
func (o *Condition) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Condition) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type, true
}

// SetType sets field value
func (o *Condition) SetType(v string) *Condition {
	o.Type = &v
	return o
}

func (o Condition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Condition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableCondition struct {
	value *Condition
	isSet bool
}

func (v *NullableCondition) Get() *Condition {
	return v.value
}

func (v *NullableCondition) Set(val *Condition) {
	v.value = val
	v.isSet = true
}

func (v *NullableCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCondition(val *Condition) *NullableCondition {
	return &NullableCondition{value: val, isSet: true}
}

func (v NullableCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
