/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package helmchart

import (
	"encoding/json"
	"errors"

	"github.com/kubevela/vela-go-sdk/pkg/apis/utils"
)

// checks if the HealthStatus type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &HealthStatus{}

// HealthStatus struct for HealthStatus
type HealthStatus struct {
	Condition *Condition `json:"condition"`
	Resource  *Resource  `json:"resource"`
}

// NewHealthStatusWith instantiates a new HealthStatus object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewHealthStatusWith(condition Condition, resource Resource) *HealthStatus {
	this := HealthStatus{}
	this.Condition = &condition
	this.Resource = &resource
	return &this
}

// NewHealthStatusWithDefault instantiates a new HealthStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthStatusWithDefault() *HealthStatus {
	this := HealthStatus{}
	return &this
}

// NewHealthStatus is short for NewHealthStatusWithDefault which instantiates a new HealthStatus object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthStatus() *HealthStatus {
	return NewHealthStatusWithDefault()
}

// NewHealthStatusEmpty instantiates a new HealthStatus object with no properties set.
// This constructor will not assign any default values to properties.
func NewHealthStatusEmpty() *HealthStatus {
	this := HealthStatus{}
	return &this
}

// NewHealthStatuss converts a list HealthStatus pointers to objects.
// This is helpful when the SetHealthStatus requires a list of objects
func NewHealthStatusList(ps ...*HealthStatus) []HealthStatus {
	objs := []HealthStatus{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this HealthStatus
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *HealthStatus) Validate() error {
	if o.Condition == nil {
		return errors.New("Condition in HealthStatus must be set")
	}
	if o.Resource == nil {
		return errors.New("Resource in HealthStatus must be set")
	}
	// validate all nested properties
	if o.Condition != nil {
		if err := o.Condition.Validate(); err != nil {
			return err
		}
	}
	if o.Resource != nil {
		if err := o.Resource.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// GetCondition returns the Condition field value
func (o *HealthStatus) GetCondition() Condition {
	if o == nil {
		var ret Condition
		return ret
	}

	return *o.Condition
}

// GetConditionOk returns a tuple with the Condition field value
// and a boolean to check if the value has been set.
func (o *HealthStatus) GetConditionOk() (*Condition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Condition, true
}

// SetCondition sets field value
func (o *HealthStatus) SetCondition(v Condition) *HealthStatus {
	o.Condition = &v
	return o
}

// GetResource returns the Resource field value
func (o *HealthStatus) GetResource() Resource {
	if o == nil {
		var ret Resource
		return ret
	}

	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *HealthStatus) GetResourceOk() (*Resource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Resource, true
}

// SetResource sets field value
func (o *HealthStatus) SetResource(v Resource) *HealthStatus {
	o.Resource = &v
	return o
}

func (o HealthStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["condition"] = o.Condition
	toSerialize["resource"] = o.Resource
	return toSerialize, nil
}

type NullableHealthStatus struct {
	value *HealthStatus
	isSet bool
}

func (v *NullableHealthStatus) Get() *HealthStatus {
	return v.value
}

func (v *NullableHealthStatus) Set(val *HealthStatus) {
	v.value = val
	v.isSet = true
}

func (v *NullableHealthStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthStatus(val *HealthStatus) *NullableHealthStatus {
	return &NullableHealthStatus{value: val, isSet: true}
}

func (v NullableHealthStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
