/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package helmchart

import (
	"encoding/json"
	"errors"
	"fmt"

	"github.com/oam-dev/kubevela-core-api/apis/core.oam.dev/common"
	"github.com/oam-dev/kubevela-core-api/pkg/oam/util"

	"github.com/kubevela/pkg/apis/oam/v1alpha1"
	"github.com/kubevela/vela-go-sdk/pkg/apis"
	sdkcommon "github.com/kubevela/vela-go-sdk/pkg/apis/common"
	"github.com/kubevela/vela-go-sdk/pkg/apis/utils"
)

// checks if the HelmchartSpec type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &HelmchartSpec{}

// HelmchartSpec struct for HelmchartSpec
type HelmchartSpec struct {
	Chart        *Chart         `json:"chart"`
	HealthStatus []HealthStatus `json:"healthStatus,omitempty"`
	Options      *Options       `json:"options,omitempty"`
	Release      *Release       `json:"release,omitempty"`
	// Inline values merged with the highest priority; override everything in valuesFrom.
	Values map[string]interface{} `json:"values,omitempty"`
	// Additional values sources merged in array order. Later entries override earlier ones on conflict, and inline `values` override everything in valuesFrom. Deep-merges map keys; arrays are replaced (not concatenated); null is preserved. On every reconcile the controller computes a content fingerprint over all referenced sources and folds it into the workflow revision; an external edit to a referenced ConfigMap/Secret triggers a `helm upgrade` on the next reconcile (default resync ~5 min). Sources are read from the control-plane cluster regardless of where the chart is deployed. Suppressed when the `app.oam.dev/publishVersion` annotation is set so explicit pins remain hard.
	ValuesFrom []ValuesFrom `json:"valuesFrom,omitempty"`
}

// NewHelmchartSpecWith instantiates a new HelmchartSpec object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewHelmchartSpecWith(chart Chart) *HelmchartSpec {
	this := HelmchartSpec{}
	this.Chart = &chart
	return &this
}

// NewHelmchartSpecWithDefault instantiates a new HelmchartSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelmchartSpecWithDefault() *HelmchartSpec {
	this := HelmchartSpec{}
	return &this
}

// NewHelmchartSpec is short for NewHelmchartSpecWithDefault which instantiates a new HelmchartSpec object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelmchartSpec() *HelmchartSpec {
	return NewHelmchartSpecWithDefault()
}

// NewHelmchartSpecEmpty instantiates a new HelmchartSpec object with no properties set.
// This constructor will not assign any default values to properties.
func NewHelmchartSpecEmpty() *HelmchartSpec {
	this := HelmchartSpec{}
	return &this
}

// NewHelmchartSpecs converts a list HelmchartSpec pointers to objects.
// This is helpful when the SetHelmchartSpec requires a list of objects
func NewHelmchartSpecList(ps ...*HelmchartSpec) []HelmchartSpec {
	objs := []HelmchartSpec{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this HelmchartSpec
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *HelmchartComponent) Validate() error {
	if o.Properties.Chart == nil {
		return errors.New("Chart in HelmchartSpec must be set")
	}
	// validate all nested properties
	if o.Properties.Chart != nil {
		if err := o.Properties.Chart.Validate(); err != nil {
			return err
		}
	}
	if o.Properties.Options != nil {
		if err := o.Properties.Options.Validate(); err != nil {
			return err
		}
	}
	if o.Properties.Release != nil {
		if err := o.Properties.Release.Validate(); err != nil {
			return err
		}
	}

	for i, v := range o.Base.Traits {
		if err := v.Validate(); err != nil {
			return fmt.Errorf("traits[%d] %s in %s component is invalid: %w", i, v.DefType(), HelmchartType, err)
		}
	}
	return nil
}

// GetChart returns the Chart field value
func (o *HelmchartComponent) GetChart() Chart {
	if o == nil {
		var ret Chart
		return ret
	}

	return *o.Properties.Chart
}

// GetChartOk returns a tuple with the Chart field value
// and a boolean to check if the value has been set.
func (o *HelmchartComponent) GetChartOk() (*Chart, bool) {
	if o == nil {
		return nil, false
	}
	return o.Properties.Chart, true
}

// SetChart sets field value
func (o *HelmchartComponent) SetChart(v Chart) *HelmchartComponent {
	o.Properties.Chart = &v
	return o
}

// GetHealthStatus returns the HealthStatus field value if set, zero value otherwise.
func (o *HelmchartComponent) GetHealthStatus() []HealthStatus {
	if o == nil || utils.IsNil(o.Properties.HealthStatus) {
		var ret []HealthStatus
		return ret
	}
	return o.Properties.HealthStatus
}

// GetHealthStatusOk returns a tuple with the HealthStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelmchartComponent) GetHealthStatusOk() ([]HealthStatus, bool) {
	if o == nil || utils.IsNil(o.Properties.HealthStatus) {
		return nil, false
	}
	return o.Properties.HealthStatus, true
}

// HasHealthStatus returns a boolean if a field has been set.
func (o *HelmchartComponent) HasHealthStatus() bool {
	if o != nil && !utils.IsNil(o.Properties.HealthStatus) {
		return true
	}

	return false
}

// SetHealthStatus gets a reference to the given []HealthStatus and assigns it to the healthStatus field.
// HealthStatus:
func (o *HelmchartComponent) SetHealthStatus(v []HealthStatus) *HelmchartComponent {
	o.Properties.HealthStatus = v
	return o
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *HelmchartComponent) GetOptions() Options {
	if o == nil || utils.IsNil(o.Properties.Options) {
		var ret Options
		return ret
	}
	return *o.Properties.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelmchartComponent) GetOptionsOk() (*Options, bool) {
	if o == nil || utils.IsNil(o.Properties.Options) {
		return nil, false
	}
	return o.Properties.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *HelmchartComponent) HasOptions() bool {
	if o != nil && !utils.IsNil(o.Properties.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given Options and assigns it to the options field.
// Options:
func (o *HelmchartComponent) SetOptions(v Options) *HelmchartComponent {
	o.Properties.Options = &v
	return o
}

// GetRelease returns the Release field value if set, zero value otherwise.
func (o *HelmchartComponent) GetRelease() Release {
	if o == nil || utils.IsNil(o.Properties.Release) {
		var ret Release
		return ret
	}
	return *o.Properties.Release
}

// GetReleaseOk returns a tuple with the Release field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelmchartComponent) GetReleaseOk() (*Release, bool) {
	if o == nil || utils.IsNil(o.Properties.Release) {
		return nil, false
	}
	return o.Properties.Release, true
}

// HasRelease returns a boolean if a field has been set.
func (o *HelmchartComponent) HasRelease() bool {
	if o != nil && !utils.IsNil(o.Properties.Release) {
		return true
	}

	return false
}

// SetRelease gets a reference to the given Release and assigns it to the release field.
// Release:
func (o *HelmchartComponent) SetRelease(v Release) *HelmchartComponent {
	o.Properties.Release = &v
	return o
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *HelmchartComponent) GetValues() map[string]interface{} {
	if o == nil || utils.IsNil(o.Properties.Values) {
		var ret map[string]interface{}
		return ret
	}
	return o.Properties.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelmchartComponent) GetValuesOk() (map[string]interface{}, bool) {
	if o == nil || utils.IsNil(o.Properties.Values) {
		return map[string]interface{}{}, false
	}
	return o.Properties.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *HelmchartComponent) HasValues() bool {
	if o != nil && !utils.IsNil(o.Properties.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given map[string]interface{} and assigns it to the values field.
// Values:  Inline values merged with the highest priority; override everything in valuesFrom.
func (o *HelmchartComponent) SetValues(v map[string]interface{}) *HelmchartComponent {
	o.Properties.Values = v
	return o
}

// GetValuesFrom returns the ValuesFrom field value if set, zero value otherwise.
func (o *HelmchartComponent) GetValuesFrom() []ValuesFrom {
	if o == nil || utils.IsNil(o.Properties.ValuesFrom) {
		var ret []ValuesFrom
		return ret
	}
	return o.Properties.ValuesFrom
}

// GetValuesFromOk returns a tuple with the ValuesFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HelmchartComponent) GetValuesFromOk() ([]ValuesFrom, bool) {
	if o == nil || utils.IsNil(o.Properties.ValuesFrom) {
		return nil, false
	}
	return o.Properties.ValuesFrom, true
}

// HasValuesFrom returns a boolean if a field has been set.
func (o *HelmchartComponent) HasValuesFrom() bool {
	if o != nil && !utils.IsNil(o.Properties.ValuesFrom) {
		return true
	}

	return false
}

// SetValuesFrom gets a reference to the given []ValuesFrom and assigns it to the valuesFrom field.
// ValuesFrom:  Additional values sources merged in array order. Later entries override earlier ones on conflict, and inline `values` override everything in valuesFrom. Deep-merges map keys; arrays are replaced (not concatenated); null is preserved. On every reconcile the controller computes a content fingerprint over all referenced sources and folds it into the workflow revision; an external edit to a referenced ConfigMap/Secret triggers a `helm upgrade` on the next reconcile (default resync ~5 min). Sources are read from the control-plane cluster regardless of where the chart is deployed. Suppressed when the `app.oam.dev/publishVersion` annotation is set so explicit pins remain hard.
func (o *HelmchartComponent) SetValuesFrom(v []ValuesFrom) *HelmchartComponent {
	o.Properties.ValuesFrom = v
	return o
}

func (o HelmchartSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelmchartSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chart"] = o.Chart
	if !utils.IsNil(o.HealthStatus) {
		toSerialize["healthStatus"] = o.HealthStatus
	}
	if !utils.IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	if !utils.IsNil(o.Release) {
		toSerialize["release"] = o.Release
	}
	if !utils.IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	if !utils.IsNil(o.ValuesFrom) {
		toSerialize["valuesFrom"] = o.ValuesFrom
	}
	return toSerialize, nil
}

type NullableHelmchartSpec struct {
	value *HelmchartSpec
	isSet bool
}

func (v *NullableHelmchartSpec) Get() *HelmchartSpec {
	return v.value
}

func (v *NullableHelmchartSpec) Set(val *HelmchartSpec) {
	v.value = val
	v.isSet = true
}

func (v *NullableHelmchartSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableHelmchartSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelmchartSpec(val *HelmchartSpec) *NullableHelmchartSpec {
	return &NullableHelmchartSpec{value: val, isSet: true}
}

func (v NullableHelmchartSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelmchartSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

const HelmchartType = "helmchart"

func init() {
	sdkcommon.RegisterComponent(HelmchartType, FromComponent)
}

type HelmchartComponent struct {
	Base       apis.ComponentBase
	Properties HelmchartSpec
}

func Helmchart(name string) *HelmchartComponent {
	h := &HelmchartComponent{Base: apis.ComponentBase{
		Name: name,
		Type: HelmchartType,
	}}
	return h
}

func (h *HelmchartComponent) Build() common.ApplicationComponent {
	traits := make([]common.ApplicationTrait, 0)
	for _, trait := range h.Base.Traits {
		traits = append(traits, trait.Build())
	}
	res := common.ApplicationComponent{
		DependsOn:  h.Base.DependsOn,
		Inputs:     h.Base.Inputs,
		Name:       h.Base.Name,
		Outputs:    h.Base.Outputs,
		Properties: util.Object2RawExtension(h.Properties),
		Traits:     traits,
		Type:       HelmchartType,
	}
	return res
}

func (h *HelmchartComponent) FromComponent(from common.ApplicationComponent) (*HelmchartComponent, error) {
	for _, trait := range from.Traits {
		_t, err := sdkcommon.FromTrait(trait)
		if err != nil {
			return nil, err
		}
		h.Base.Traits = append(h.Base.Traits, _t)
	}
	var properties HelmchartSpec
	if from.Properties != nil {
		err := json.Unmarshal(from.Properties.Raw, &properties)
		if err != nil {
			return nil, err
		}
	}
	h.Base.Name = from.Name
	h.Base.DependsOn = from.DependsOn
	h.Base.Inputs = from.Inputs
	h.Base.Outputs = from.Outputs
	h.Base.Type = HelmchartType
	h.Properties = properties
	return h, nil
}

func FromComponent(from common.ApplicationComponent) (apis.Component, error) {
	h := &HelmchartComponent{}
	return h.FromComponent(from)
}

func (h *HelmchartComponent) SetTraits(traits ...apis.Trait) *HelmchartComponent {
	for _, addTrait := range traits {
		found := false
		for i, _t := range h.Base.Traits {
			if _t.DefType() == addTrait.DefType() {
				h.Base.Traits[i] = addTrait
				found = true
				break
			}
		}
		if !found {
			h.Base.Traits = append(h.Base.Traits, addTrait)
		}
	}
	return h
}

func (h *HelmchartComponent) GetTrait(typ string) apis.Trait {
	for _, _t := range h.Base.Traits {
		if _t.DefType() == typ {
			return _t
		}
	}
	return nil
}

func (h *HelmchartComponent) GetAllTraits() []apis.Trait {
	return h.Base.Traits
}

func (h *HelmchartComponent) ComponentName() string {
	return h.Base.Name
}

func (h *HelmchartComponent) DefType() string {
	return HelmchartType
}

func (h *HelmchartComponent) DependsOn(dependsOn []string) *HelmchartComponent {
	h.Base.DependsOn = dependsOn
	return h
}

func (h *HelmchartComponent) Inputs(input v1alpha1.StepInputs) *HelmchartComponent {
	h.Base.Inputs = input
	return h
}

func (h *HelmchartComponent) Outputs(output v1alpha1.StepOutputs) *HelmchartComponent {
	h.Base.Outputs = output
	return h
}

func (h *HelmchartComponent) AddDependsOn(dependsOn string) *HelmchartComponent {
	h.Base.DependsOn = append(h.Base.DependsOn, dependsOn)
	return h
}
