/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package helmchart

import (
	"encoding/json"

	"github.com/kubevela/vela-go-sdk/pkg/apis/utils"
)

// checks if the Options type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Options{}

// Options struct for Options
type Options struct {
	Atomic          *bool   `json:"atomic,omitempty"`
	Cache           *Cache  `json:"cache,omitempty"`
	CleanupOnFail   *bool   `json:"cleanupOnFail,omitempty"`
	CreateNamespace *bool   `json:"createNamespace,omitempty"`
	Force           *bool   `json:"force,omitempty"`
	IncludeCRDs     *bool   `json:"includeCRDs,omitempty"`
	MaxHistory      *int32  `json:"maxHistory,omitempty"`
	RecreatePods    *bool   `json:"recreatePods,omitempty"`
	SkipHooks       *bool   `json:"skipHooks,omitempty"`
	SkipTests       *bool   `json:"skipTests,omitempty"`
	Timeout         *string `json:"timeout,omitempty"`
	Wait            *bool   `json:"wait,omitempty"`
}

// NewOptionsWith instantiates a new Options object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewOptionsWith() *Options {
	this := Options{}
	var atomic bool = false
	this.Atomic = &atomic
	var cleanupOnFail bool = false
	this.CleanupOnFail = &cleanupOnFail
	var createNamespace bool = true
	this.CreateNamespace = &createNamespace
	var force bool = false
	this.Force = &force
	var includeCRDs bool = true
	this.IncludeCRDs = &includeCRDs
	var maxHistory int32 = 10
	this.MaxHistory = &maxHistory
	var recreatePods bool = false
	this.RecreatePods = &recreatePods
	var skipHooks bool = false
	this.SkipHooks = &skipHooks
	var skipTests bool = true
	this.SkipTests = &skipTests
	var timeout string = "5m"
	this.Timeout = &timeout
	var wait bool = false
	this.Wait = &wait
	return &this
}

// NewOptionsWithDefault instantiates a new Options object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOptionsWithDefault() *Options {
	this := Options{}
	var atomic bool = false
	this.Atomic = &atomic
	var cleanupOnFail bool = false
	this.CleanupOnFail = &cleanupOnFail
	var createNamespace bool = true
	this.CreateNamespace = &createNamespace
	var force bool = false
	this.Force = &force
	var includeCRDs bool = true
	this.IncludeCRDs = &includeCRDs
	var maxHistory int32 = 10
	this.MaxHistory = &maxHistory
	var recreatePods bool = false
	this.RecreatePods = &recreatePods
	var skipHooks bool = false
	this.SkipHooks = &skipHooks
	var skipTests bool = true
	this.SkipTests = &skipTests
	var timeout string = "5m"
	this.Timeout = &timeout
	var wait bool = false
	this.Wait = &wait
	return &this
}

// NewOptions is short for NewOptionsWithDefault which instantiates a new Options object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOptions() *Options {
	return NewOptionsWithDefault()
}

// NewOptionsEmpty instantiates a new Options object with no properties set.
// This constructor will not assign any default values to properties.
func NewOptionsEmpty() *Options {
	this := Options{}
	return &this
}

// NewOptionss converts a list Options pointers to objects.
// This is helpful when the SetOptions requires a list of objects
func NewOptionsList(ps ...*Options) []Options {
	objs := []Options{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this Options
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *Options) Validate() error {
	// validate all nested properties
	if o.Cache != nil {
		if err := o.Cache.Validate(); err != nil {
			return err
		}
	}
	return nil
}

// GetAtomic returns the Atomic field value if set, zero value otherwise.
func (o *Options) GetAtomic() bool {
	if o == nil || utils.IsNil(o.Atomic) {
		var ret bool
		return ret
	}
	return *o.Atomic
}

// GetAtomicOk returns a tuple with the Atomic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Options) GetAtomicOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.Atomic) {
		return nil, false
	}
	return o.Atomic, true
}

// HasAtomic returns a boolean if a field has been set.
func (o *Options) HasAtomic() bool {
	if o != nil && !utils.IsNil(o.Atomic) {
		return true
	}

	return false
}

// SetAtomic gets a reference to the given bool and assigns it to the atomic field.
// Atomic:
func (o *Options) SetAtomic(v bool) *Options {
	o.Atomic = &v
	return o
}

// GetCache returns the Cache field value if set, zero value otherwise.
func (o *Options) GetCache() Cache {
	if o == nil || utils.IsNil(o.Cache) {
		var ret Cache
		return ret
	}
	return *o.Cache
}

// GetCacheOk returns a tuple with the Cache field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Options) GetCacheOk() (*Cache, bool) {
	if o == nil || utils.IsNil(o.Cache) {
		return nil, false
	}
	return o.Cache, true
}

// HasCache returns a boolean if a field has been set.
func (o *Options) HasCache() bool {
	if o != nil && !utils.IsNil(o.Cache) {
		return true
	}

	return false
}

// SetCache gets a reference to the given Cache and assigns it to the cache field.
// Cache:
func (o *Options) SetCache(v Cache) *Options {
	o.Cache = &v
	return o
}

// GetCleanupOnFail returns the CleanupOnFail field value if set, zero value otherwise.
func (o *Options) GetCleanupOnFail() bool {
	if o == nil || utils.IsNil(o.CleanupOnFail) {
		var ret bool
		return ret
	}
	return *o.CleanupOnFail
}

// GetCleanupOnFailOk returns a tuple with the CleanupOnFail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Options) GetCleanupOnFailOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.CleanupOnFail) {
		return nil, false
	}
	return o.CleanupOnFail, true
}

// HasCleanupOnFail returns a boolean if a field has been set.
func (o *Options) HasCleanupOnFail() bool {
	if o != nil && !utils.IsNil(o.CleanupOnFail) {
		return true
	}

	return false
}

// SetCleanupOnFail gets a reference to the given bool and assigns it to the cleanupOnFail field.
// CleanupOnFail:
func (o *Options) SetCleanupOnFail(v bool) *Options {
	o.CleanupOnFail = &v
	return o
}

// GetCreateNamespace returns the CreateNamespace field value if set, zero value otherwise.
func (o *Options) GetCreateNamespace() bool {
	if o == nil || utils.IsNil(o.CreateNamespace) {
		var ret bool
		return ret
	}
	return *o.CreateNamespace
}

// GetCreateNamespaceOk returns a tuple with the CreateNamespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Options) GetCreateNamespaceOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.CreateNamespace) {
		return nil, false
	}
	return o.CreateNamespace, true
}

// HasCreateNamespace returns a boolean if a field has been set.
func (o *Options) HasCreateNamespace() bool {
	if o != nil && !utils.IsNil(o.CreateNamespace) {
		return true
	}

	return false
}

// SetCreateNamespace gets a reference to the given bool and assigns it to the createNamespace field.
// CreateNamespace:
func (o *Options) SetCreateNamespace(v bool) *Options {
	o.CreateNamespace = &v
	return o
}

// GetForce returns the Force field value if set, zero value otherwise.
func (o *Options) GetForce() bool {
	if o == nil || utils.IsNil(o.Force) {
		var ret bool
		return ret
	}
	return *o.Force
}

// GetForceOk returns a tuple with the Force field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Options) GetForceOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.Force) {
		return nil, false
	}
	return o.Force, true
}

// HasForce returns a boolean if a field has been set.
func (o *Options) HasForce() bool {
	if o != nil && !utils.IsNil(o.Force) {
		return true
	}

	return false
}

// SetForce gets a reference to the given bool and assigns it to the force field.
// Force:
func (o *Options) SetForce(v bool) *Options {
	o.Force = &v
	return o
}

// GetIncludeCRDs returns the IncludeCRDs field value if set, zero value otherwise.
func (o *Options) GetIncludeCRDs() bool {
	if o == nil || utils.IsNil(o.IncludeCRDs) {
		var ret bool
		return ret
	}
	return *o.IncludeCRDs
}

// GetIncludeCRDsOk returns a tuple with the IncludeCRDs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Options) GetIncludeCRDsOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.IncludeCRDs) {
		return nil, false
	}
	return o.IncludeCRDs, true
}

// HasIncludeCRDs returns a boolean if a field has been set.
func (o *Options) HasIncludeCRDs() bool {
	if o != nil && !utils.IsNil(o.IncludeCRDs) {
		return true
	}

	return false
}

// SetIncludeCRDs gets a reference to the given bool and assigns it to the includeCRDs field.
// IncludeCRDs:
func (o *Options) SetIncludeCRDs(v bool) *Options {
	o.IncludeCRDs = &v
	return o
}

// GetMaxHistory returns the MaxHistory field value if set, zero value otherwise.
func (o *Options) GetMaxHistory() int32 {
	if o == nil || utils.IsNil(o.MaxHistory) {
		var ret int32
		return ret
	}
	return *o.MaxHistory
}

// GetMaxHistoryOk returns a tuple with the MaxHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Options) GetMaxHistoryOk() (*int32, bool) {
	if o == nil || utils.IsNil(o.MaxHistory) {
		return nil, false
	}
	return o.MaxHistory, true
}

// HasMaxHistory returns a boolean if a field has been set.
func (o *Options) HasMaxHistory() bool {
	if o != nil && !utils.IsNil(o.MaxHistory) {
		return true
	}

	return false
}

// SetMaxHistory gets a reference to the given int32 and assigns it to the maxHistory field.
// MaxHistory:
func (o *Options) SetMaxHistory(v int32) *Options {
	o.MaxHistory = &v
	return o
}

// GetRecreatePods returns the RecreatePods field value if set, zero value otherwise.
func (o *Options) GetRecreatePods() bool {
	if o == nil || utils.IsNil(o.RecreatePods) {
		var ret bool
		return ret
	}
	return *o.RecreatePods
}

// GetRecreatePodsOk returns a tuple with the RecreatePods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Options) GetRecreatePodsOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.RecreatePods) {
		return nil, false
	}
	return o.RecreatePods, true
}

// HasRecreatePods returns a boolean if a field has been set.
func (o *Options) HasRecreatePods() bool {
	if o != nil && !utils.IsNil(o.RecreatePods) {
		return true
	}

	return false
}

// SetRecreatePods gets a reference to the given bool and assigns it to the recreatePods field.
// RecreatePods:
func (o *Options) SetRecreatePods(v bool) *Options {
	o.RecreatePods = &v
	return o
}

// GetSkipHooks returns the SkipHooks field value if set, zero value otherwise.
func (o *Options) GetSkipHooks() bool {
	if o == nil || utils.IsNil(o.SkipHooks) {
		var ret bool
		return ret
	}
	return *o.SkipHooks
}

// GetSkipHooksOk returns a tuple with the SkipHooks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Options) GetSkipHooksOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.SkipHooks) {
		return nil, false
	}
	return o.SkipHooks, true
}

// HasSkipHooks returns a boolean if a field has been set.
func (o *Options) HasSkipHooks() bool {
	if o != nil && !utils.IsNil(o.SkipHooks) {
		return true
	}

	return false
}

// SetSkipHooks gets a reference to the given bool and assigns it to the skipHooks field.
// SkipHooks:
func (o *Options) SetSkipHooks(v bool) *Options {
	o.SkipHooks = &v
	return o
}

// GetSkipTests returns the SkipTests field value if set, zero value otherwise.
func (o *Options) GetSkipTests() bool {
	if o == nil || utils.IsNil(o.SkipTests) {
		var ret bool
		return ret
	}
	return *o.SkipTests
}

// GetSkipTestsOk returns a tuple with the SkipTests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Options) GetSkipTestsOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.SkipTests) {
		return nil, false
	}
	return o.SkipTests, true
}

// HasSkipTests returns a boolean if a field has been set.
func (o *Options) HasSkipTests() bool {
	if o != nil && !utils.IsNil(o.SkipTests) {
		return true
	}

	return false
}

// SetSkipTests gets a reference to the given bool and assigns it to the skipTests field.
// SkipTests:
func (o *Options) SetSkipTests(v bool) *Options {
	o.SkipTests = &v
	return o
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *Options) GetTimeout() string {
	if o == nil || utils.IsNil(o.Timeout) {
		var ret string
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Options) GetTimeoutOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *Options) HasTimeout() bool {
	if o != nil && !utils.IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given string and assigns it to the timeout field.
// Timeout:
func (o *Options) SetTimeout(v string) *Options {
	o.Timeout = &v
	return o
}

// GetWait returns the Wait field value if set, zero value otherwise.
func (o *Options) GetWait() bool {
	if o == nil || utils.IsNil(o.Wait) {
		var ret bool
		return ret
	}
	return *o.Wait
}

// GetWaitOk returns a tuple with the Wait field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Options) GetWaitOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.Wait) {
		return nil, false
	}
	return o.Wait, true
}

// HasWait returns a boolean if a field has been set.
func (o *Options) HasWait() bool {
	if o != nil && !utils.IsNil(o.Wait) {
		return true
	}

	return false
}

// SetWait gets a reference to the given bool and assigns it to the wait field.
// Wait:
func (o *Options) SetWait(v bool) *Options {
	o.Wait = &v
	return o
}

func (o Options) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Options) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Atomic) {
		toSerialize["atomic"] = o.Atomic
	}
	if !utils.IsNil(o.Cache) {
		toSerialize["cache"] = o.Cache
	}
	if !utils.IsNil(o.CleanupOnFail) {
		toSerialize["cleanupOnFail"] = o.CleanupOnFail
	}
	if !utils.IsNil(o.CreateNamespace) {
		toSerialize["createNamespace"] = o.CreateNamespace
	}
	if !utils.IsNil(o.Force) {
		toSerialize["force"] = o.Force
	}
	if !utils.IsNil(o.IncludeCRDs) {
		toSerialize["includeCRDs"] = o.IncludeCRDs
	}
	if !utils.IsNil(o.MaxHistory) {
		toSerialize["maxHistory"] = o.MaxHistory
	}
	if !utils.IsNil(o.RecreatePods) {
		toSerialize["recreatePods"] = o.RecreatePods
	}
	if !utils.IsNil(o.SkipHooks) {
		toSerialize["skipHooks"] = o.SkipHooks
	}
	if !utils.IsNil(o.SkipTests) {
		toSerialize["skipTests"] = o.SkipTests
	}
	if !utils.IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	if !utils.IsNil(o.Wait) {
		toSerialize["wait"] = o.Wait
	}
	return toSerialize, nil
}

type NullableOptions struct {
	value *Options
	isSet bool
}

func (v *NullableOptions) Get() *Options {
	return v.value
}

func (v *NullableOptions) Set(val *Options) {
	v.value = val
	v.isSet = true
}

func (v *NullableOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOptions(val *Options) *NullableOptions {
	return &NullableOptions{value: val, isSet: true}
}

func (v NullableOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
