/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package helmchart

import (
	"encoding/json"
	"errors"

	"github.com/kubevela/vela-go-sdk/pkg/apis/utils"
)

// checks if the ValuesFrom type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &ValuesFrom{}

// ValuesFrom struct for ValuesFrom
type ValuesFrom struct {
	// Key inside .data whose value is parsed as YAML. Defaults to \"values.yaml\" (FluxCD / Helm convention). Only ConfigMap.data and Secret.data are read; ConfigMap.binaryData is rejected.
	Key *string `json:"key,omitempty"`
	// Source kind. Only Secret and ConfigMap are supported; OCIRepository is reserved for a future release.
	Kind *string `json:"kind"`
	// Name of the Secret or ConfigMap.
	Name *string `json:"name"`
	// Namespace of the Secret or ConfigMap. Defaults to the chart release namespace, which itself defaults to the Application's own namespace when release.namespace is unset. Cross-namespace references are rejected to prevent cross-tenant reads via the controller's cluster-wide RBAC.
	Namespace *string `json:"namespace,omitempty"`
	// If true, a missing Secret/ConfigMap or missing key is skipped silently. Parse errors and permission errors still fail the render.
	Optional *bool `json:"optional,omitempty"`
}

// NewValuesFromWith instantiates a new ValuesFrom object
// This constructor will make sure properties required by API are set.
// For optional properties, it will set default values if they have been defined.
// The set of arguments will change when the set of required properties is changed
func NewValuesFromWith(kind string, name string) *ValuesFrom {
	this := ValuesFrom{}
	this.Kind = &kind
	this.Name = &name
	var optional bool = false
	this.Optional = &optional
	return &this
}

// NewValuesFromWithDefault instantiates a new ValuesFrom object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValuesFromWithDefault() *ValuesFrom {
	this := ValuesFrom{}
	var optional bool = false
	this.Optional = &optional
	return &this
}

// NewValuesFrom is short for NewValuesFromWithDefault which instantiates a new ValuesFrom object.
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValuesFrom() *ValuesFrom {
	return NewValuesFromWithDefault()
}

// NewValuesFromEmpty instantiates a new ValuesFrom object with no properties set.
// This constructor will not assign any default values to properties.
func NewValuesFromEmpty() *ValuesFrom {
	this := ValuesFrom{}
	return &this
}

// NewValuesFroms converts a list ValuesFrom pointers to objects.
// This is helpful when the SetValuesFrom requires a list of objects
func NewValuesFromList(ps ...*ValuesFrom) []ValuesFrom {
	objs := []ValuesFrom{}
	for _, p := range ps {
		objs = append(objs, *p)
	}
	return objs
}

// Validate validates this ValuesFrom
// 1. If the required properties are not set, this will return an error
// 2. If properties are set, will check if nested required properties are set
func (o *ValuesFrom) Validate() error {
	if o.Kind == nil {
		return errors.New("Kind in ValuesFrom must be set")
	}
	if o.Name == nil {
		return errors.New("Name in ValuesFrom must be set")
	}
	// validate all nested properties
	return nil
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ValuesFrom) GetKey() string {
	if o == nil || utils.IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValuesFrom) GetKeyOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ValuesFrom) HasKey() bool {
	if o != nil && !utils.IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the key field.
// Key:  Key inside .data whose value is parsed as YAML. Defaults to \"values.yaml\" (FluxCD / Helm convention). Only ConfigMap.data and Secret.data are read; ConfigMap.binaryData is rejected.
func (o *ValuesFrom) SetKey(v string) *ValuesFrom {
	o.Key = &v
	return o
}

// GetKind returns the Kind field value
func (o *ValuesFrom) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *ValuesFrom) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Kind, true
}

// SetKind sets field value
func (o *ValuesFrom) SetKind(v string) *ValuesFrom {
	o.Kind = &v
	return o
}

// GetName returns the Name field value
func (o *ValuesFrom) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return *o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ValuesFrom) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name, true
}

// SetName sets field value
func (o *ValuesFrom) SetName(v string) *ValuesFrom {
	o.Name = &v
	return o
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *ValuesFrom) GetNamespace() string {
	if o == nil || utils.IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValuesFrom) GetNamespaceOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *ValuesFrom) HasNamespace() bool {
	if o != nil && !utils.IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the namespace field.
// Namespace:  Namespace of the Secret or ConfigMap. Defaults to the chart release namespace, which itself defaults to the Application's own namespace when release.namespace is unset. Cross-namespace references are rejected to prevent cross-tenant reads via the controller's cluster-wide RBAC.
func (o *ValuesFrom) SetNamespace(v string) *ValuesFrom {
	o.Namespace = &v
	return o
}

// GetOptional returns the Optional field value if set, zero value otherwise.
func (o *ValuesFrom) GetOptional() bool {
	if o == nil || utils.IsNil(o.Optional) {
		var ret bool
		return ret
	}
	return *o.Optional
}

// GetOptionalOk returns a tuple with the Optional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValuesFrom) GetOptionalOk() (*bool, bool) {
	if o == nil || utils.IsNil(o.Optional) {
		return nil, false
	}
	return o.Optional, true
}

// HasOptional returns a boolean if a field has been set.
func (o *ValuesFrom) HasOptional() bool {
	if o != nil && !utils.IsNil(o.Optional) {
		return true
	}

	return false
}

// SetOptional gets a reference to the given bool and assigns it to the optional field.
// Optional:  If true, a missing Secret/ConfigMap or missing key is skipped silently. Parse errors and permission errors still fail the render.
func (o *ValuesFrom) SetOptional(v bool) *ValuesFrom {
	o.Optional = &v
	return o
}

func (o ValuesFrom) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValuesFrom) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	toSerialize["kind"] = o.Kind
	toSerialize["name"] = o.Name
	if !utils.IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !utils.IsNil(o.Optional) {
		toSerialize["optional"] = o.Optional
	}
	return toSerialize, nil
}

type NullableValuesFrom struct {
	value *ValuesFrom
	isSet bool
}

func (v *NullableValuesFrom) Get() *ValuesFrom {
	return v.value
}

func (v *NullableValuesFrom) Set(val *ValuesFrom) {
	v.value = val
	v.isSet = true
}

func (v *NullableValuesFrom) IsSet() bool {
	return v.isSet
}

func (v *NullableValuesFrom) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValuesFrom(val *ValuesFrom) *NullableValuesFrom {
	return &NullableValuesFrom{value: val, isSet: true}
}

func (v NullableValuesFrom) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValuesFrom) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
