apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: rttest-merge
  namespace: vela-system
spec:
  workload:
    definition:
      apiVersion: v1
      kind: ConfigMap
  schematic:
    cue:
      template: |
        import (
          "list"
          "strings"
        )

        output: {
          apiVersion: "v1"
          kind:       "ConfigMap"
          metadata: name: parameter.name
          data: {
            allLabels:        strings.Join(list.Concat([parameter.left, parameter.right]), ",")
            cdRevisionMarker: "v1-original-cd"
          }
        }
        parameter: {
          name:  string
          left:  [...string]
          right: [...string]
        }
