apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: comp-kube-state-metrics
  namespace: vela-system
spec:
  components:
    - name: kube-state-metrics
      type: addon
      properties:
        skipVersionValidation: true
