apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: comp-model-serving
  namespace: vela-system
spec:
  components:
    - name: model-serving
      type: addon
      properties:
        skipVersionValidation: true
