apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: comp-node-exporter
  namespace: vela-system
spec:
  components:
    - name: node-exporter
      type: addon
      properties:
        skipVersionValidation: true
