apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: comp-rollout
  namespace: vela-system
spec:
  components:
    - name: rollout
      type: addon
      properties:
        skipVersionValidation: true
