apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: comp-terraform-baidu
  namespace: vela-system
spec:
  components:
    - name: terraform-baidu
      type: addon
      properties:
        skipVersionValidation: true
