apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: comp-vela-core-shard-manager
  namespace: vela-system
spec:
  components:
    - name: vela-core-shard-manager
      type: addon
      properties:
        skipVersionValidation: true
