apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    meta.helm.sh/release-name: kubevela
    meta.helm.sh/release-namespace: vela-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: kubevela-vela-core-admission
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVZFZQcFlxRUNxY3RLcm80VWRnUnVUaThXN293d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tWMlZpYUc5dmF5QkRRVEFlRncweU5qQTVNakV3T0RBeU1qSmFGdzB6TmpBNQpNVGd3T0RBeU1qSmFNQlV4RXpBUkJnTlZCQU1NQ2xkbFltaHZiMnNnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFES2F4WTJRMDREeXNSdUMvZ1FLR0lBQk9DSGlSaHF4Z25TVU9acWNacC8KdTdpYWhpYU5MUXQ0aHRxYSs4Sld5aEdtd2ZLbHJyM3pwZ0tqRTU2T0dxUFYxU2VqZW5GVjJMRWdrZk9kTWVsYgpjWXI3SmJhU3FTb29MQ1cvRGQzaHN6cnlEQmZYc0lrUllTTzllMDNKQXl3MDNWb05GVVYxRFgwUVJ6NUFxdGduClNSYlI5YnYyTzVrL1RyVkhJMlYzSi9sbHp2OGFuOEhhak8vNzh2aVlXZ1ZUWlNyZTBOeko3LzBHcGVZUjRZT00KaHVWcFA4cC9MeGkvVndYUnZLckRUUDcvb3ZxaVc5L2JtY0RUaEJSYWUyTjBNVmN6eDBweFMwczFOT0tPS2k1UQpHdjVHczBXdUY1N25LRVE3ZjVGTEtUa0szVjJoS1NIQzlzdGYrTXZFdHFQdEFnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlF0dE85K0VjdTdlQXViaTBUOVErOHBOclpnbFRBZkJnTlZIU01FR0RBV2dCUXR0TzkrRWN1N2VBdWIKaTBUOVErOHBOclpnbFRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDNAo0MjQ3eGJNeWlnNDlHQ3R5NnR3djBFUDlGYTJCMzh2WGs1WWtPNDNsUGJqajlZdHRybmxjdHM4UUg0WDA2K1F3CnBKWlpzNFdsbHZiUVptcTVEVWVSME8vSEFaMTZYU2Z2YW9wemI1UFp6YmpmRk0xbWV0NE9OQ0ZiSFdRY2w0WU0KODVwR2dhUEpDajBKcHBCMVZzZzdkVm8zcjBYY3NPT3hyUDIxNE1oU29ucjk1SFh1MWZSRlcxSE1NN0F2WDBibwpPMnNWeUFaWXFDK0JQZXVZWFVXeFNpNGJKZkFiNldoSkIram9Lc096VkNCWFNrdDNma2QrdHl1ci82M2ZmVHdzCkZXT3JXcHJQaUloWWJhSkNTLzRWY3diYUFJR1A2WjFNYUNtaWJPUWEyUkcxcGQyYkVTZDBIOXhuZUppeTBvMjkKOXQ4dDhPWWl0V3piaFMyK015WkYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: "https://10.131.100.113:9445/mutating-core-oam-dev-v1beta1-applications"
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mutating.core.oam.dev.v1beta1.applications
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
      - core.oam.dev
    apiVersions:
      - v1beta1
    operations:
      - CREATE
      - UPDATE
    resources:
      - applications
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVZFZQcFlxRUNxY3RLcm80VWRnUnVUaThXN293d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tWMlZpYUc5dmF5QkRRVEFlRncweU5qQTVNakV3T0RBeU1qSmFGdzB6TmpBNQpNVGd3T0RBeU1qSmFNQlV4RXpBUkJnTlZCQU1NQ2xkbFltaHZiMnNnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFES2F4WTJRMDREeXNSdUMvZ1FLR0lBQk9DSGlSaHF4Z25TVU9acWNacC8KdTdpYWhpYU5MUXQ0aHRxYSs4Sld5aEdtd2ZLbHJyM3pwZ0tqRTU2T0dxUFYxU2VqZW5GVjJMRWdrZk9kTWVsYgpjWXI3SmJhU3FTb29MQ1cvRGQzaHN6cnlEQmZYc0lrUllTTzllMDNKQXl3MDNWb05GVVYxRFgwUVJ6NUFxdGduClNSYlI5YnYyTzVrL1RyVkhJMlYzSi9sbHp2OGFuOEhhak8vNzh2aVlXZ1ZUWlNyZTBOeko3LzBHcGVZUjRZT00KaHVWcFA4cC9MeGkvVndYUnZLckRUUDcvb3ZxaVc5L2JtY0RUaEJSYWUyTjBNVmN6eDBweFMwczFOT0tPS2k1UQpHdjVHczBXdUY1N25LRVE3ZjVGTEtUa0szVjJoS1NIQzlzdGYrTXZFdHFQdEFnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlF0dE85K0VjdTdlQXViaTBUOVErOHBOclpnbFRBZkJnTlZIU01FR0RBV2dCUXR0TzkrRWN1N2VBdWIKaTBUOVErOHBOclpnbFRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDNAo0MjQ3eGJNeWlnNDlHQ3R5NnR3djBFUDlGYTJCMzh2WGs1WWtPNDNsUGJqajlZdHRybmxjdHM4UUg0WDA2K1F3CnBKWlpzNFdsbHZiUVptcTVEVWVSME8vSEFaMTZYU2Z2YW9wemI1UFp6YmpmRk0xbWV0NE9OQ0ZiSFdRY2w0WU0KODVwR2dhUEpDajBKcHBCMVZzZzdkVm8zcjBYY3NPT3hyUDIxNE1oU29ucjk1SFh1MWZSRlcxSE1NN0F2WDBibwpPMnNWeUFaWXFDK0JQZXVZWFVXeFNpNGJKZkFiNldoSkIram9Lc096VkNCWFNrdDNma2QrdHl1ci82M2ZmVHdzCkZXT3JXcHJQaUloWWJhSkNTLzRWY3diYUFJR1A2WjFNYUNtaWJPUWEyUkcxcGQyYkVTZDBIOXhuZUppeTBvMjkKOXQ4dDhPWWl0V3piaFMyK015WkYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    url: "https://10.131.100.113:9445/mutating-core-oam-dev-v1beta1-componentdefinitions"
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: mutating.core.oam.dev.v1beta1.componentdefinitions
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
      - core.oam.dev
    apiVersions:
      - v1beta1
    operations:
      - CREATE
      - UPDATE
    resources:
      - componentdefinitions
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
