apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: mk-cd
  namespace: vela-system
spec:
  workload:
    definition:
      apiVersion: v1
      kind: ConfigMap
  schematic:
    cue:
      template: |
        output: {
          apiVersion: "v1"
          kind:       "ConfigMap"
          metadata: name: parameter.name
          data: {
            cdMarker: "v2"
            payload:  parameter.payload
          }
        }
        parameter: {
          name:    string
          payload: *"hello" | string
        }
