#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///

"""
CAPABILITY: Generates a container-specific .gitconfig wrapper

When the host's .gitconfig is mounted into the container at .gitconfig-host, it may
contain paths that don't exist inside the container:

1. SSL certificates: `http.sslCAInfo` pointing to a host certificate file won't work
   because that path doesn't exist in the container.

2. Credential helpers: If the credential helper uses GitHub CLI (gh) with a host
   path like `/usr/local/bin/gh`, it won't work because gh is at a different location
   in the container.

This script generates a wrapper .gitconfig that:
- Includes the host's config via git's [include] directive
- Overrides problematic settings with container-appropriate values

The host's .gitconfig-host file is never modified.
"""

import re
import sys
from pathlib import Path

HOME = Path.home()
GITCONFIG_HOST = HOME / ".gitconfig-host"
GITCONFIG = HOME / ".gitconfig"
CONTAINER_CA_BUNDLE = Path("/etc/ssl/certs/ca-certificates.crt")

# Marker to identify our generated config
GENERATED_MARKER = "# AUTO-GENERATED by git-config-sanitize.py - DO NOT EDIT"


def main() -> int:
    """Generate a wrapper .gitconfig that includes host config with overrides."""

    # If host config doesn't exist, nothing to do
    if not GITCONFIG_HOST.exists():
        print("No .gitconfig-host found, skipping wrapper generation")
        return 0

    # Check if we need to regenerate
    if GITCONFIG.exists():
        try:
            existing = GITCONFIG.read_text()
            if GENERATED_MARKER not in existing:
                # User has their own .gitconfig that's not our generated one
                # This shouldn't happen in normal flow, but don't overwrite
                print("Warning: ~/.gitconfig exists but wasn't generated by us, skipping")
                return 0
        except Exception:
            pass

    # Analyze host config to determine what overrides we need
    overrides = analyze_host_config(GITCONFIG_HOST)

    # Generate the wrapper config
    wrapper_content = generate_wrapper_config(overrides)

    try:
        GITCONFIG.write_text(wrapper_content)
        print(f"Generated ~/.gitconfig wrapper with {len(overrides)} override(s)")
        for key, info in overrides.items():
            print(f"  - {key}: {info['reason']}")
    except Exception as e:
        print(f"Error: Could not write {GITCONFIG}: {e}", file=sys.stderr)
        return 1

    return 0


def analyze_host_config(config_path: Path) -> dict:
    """
    Analyze the host config to determine what overrides are needed.

    Returns a dict of setting -> {value, reason, clear_first} for settings that need overriding.
    """
    overrides = {}

    try:
        content = config_path.read_text()
    except Exception as e:
        print(f"Warning: Could not read {config_path}: {e}", file=sys.stderr)
        return overrides

    # Check for sslCAInfo with a path that doesn't exist in container
    ssl_match = re.search(r"^\s*sslCAInfo\s*=\s*(.+)$", content, re.MULTILINE | re.IGNORECASE)
    if ssl_match:
        host_cert_path = Path(ssl_match.group(1).strip())
        if not host_cert_path.exists():
            overrides["http.sslCAInfo"] = {
                "value": str(CONTAINER_CA_BUNDLE),
                "reason": f"host path '{host_cert_path}' doesn't exist in container",
            }

    # Find all credential sections with URL patterns that have gh helpers with absolute paths
    # Matches sections like: [credential "https://github.com"]
    # followed by: helper = !/path/to/gh auth git-credential
    cred_section_pattern = re.compile(
        r'\[credential\s+"([^"]+)"\].*?helper\s*=\s*!(/[^\s]+/gh)\s+auth\s+git-credential',
        re.MULTILINE | re.DOTALL,
    )

    for match in cred_section_pattern.finditer(content):
        url = match.group(1)
        host_gh_path = match.group(2)
        if not Path(host_gh_path).exists():
            # Git stacks credential helpers, so we need to:
            # 1. Clear inherited helpers with empty "helper ="
            # 2. Set the correct PATH-based helper
            overrides[f'credential "{url}".helper'] = {
                "value": "!gh auth git-credential",
                "reason": f"host gh path '{host_gh_path}' doesn't exist in container",
                "clear_first": True,  # Signal to add empty helper= before the value
            }

    return overrides


def generate_wrapper_config(overrides: dict) -> str:
    """
    Generate the wrapper .gitconfig content.

    The wrapper includes the host config and then applies any necessary overrides.
    Settings defined after [include] override settings from the included file.
    """
    lines = [
        GENERATED_MARKER,
        "# This file includes your host .gitconfig and overrides settings that",
        "# don't work inside the container. Your host config is not modified.",
        "",
        "[include]",
        f"\tpath = {GITCONFIG_HOST}",
        "",
    ]

    # Group overrides by section
    # Each entry is (setting, value, clear_first)
    sections: dict[str, list[tuple[str, str, bool]]] = {}

    for key, info in overrides.items():
        if "." in key:
            # Handle keys like 'http.sslCAInfo' or 'credential "https://github.com".helper'
            if '"' in key:
                # Complex section like 'credential "https://github.com".helper'
                section_end = key.rfind(".")
                section = key[:section_end]
                setting = key[section_end + 1 :]
            else:
                section, setting = key.rsplit(".", 1)

            section_header = f"[{section}]"
            if section_header not in sections:
                sections[section_header] = []
            clear_first = info.get("clear_first", False)
            sections[section_header].append((setting, info["value"], clear_first))

    # Add override sections
    for section_header, settings in sections.items():
        lines.append(section_header)
        for setting, value, clear_first in settings:
            if clear_first:
                # Add empty value first to clear inherited settings (git stacks these)
                lines.append(f"\t{setting} =")
            lines.append(f"\t{setting} = {value}")
        lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    sys.exit(main())
